# Generated by Django 6.0.6 on 2026-07-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/generated/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resumes/previews/')),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('moderncv', 'Modern CV'), ('sb2nov', 'SB2Nov'), ('engineeringresumes', 'Engineering Resumes'), ('yagiz', 'Yagiz')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_name', models.CharField(blank=True, help_text='Display name for this generated PDF', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(blank=True, help_text='e.g. Software Engineer | PhD Candidate', max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='E.164 format, e.g. +1-234-567-8900', max_length=30)),
                ('website', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Optional profile photo — only included in themes that support it', null=True, upload_to='resume_photos/')),
                ('selected_theme', models.CharField(choices=[('classic', 'Classic'), ('moderncv', 'Modern CV'), ('sb2nov', 'SB2Nov'), ('engineeringresumes', 'Engineering Resumes'), ('yagiz', 'Yagiz')], default='classic', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title, e.g. "Work Experience"', max_length=200)),
                ('entry_type', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('project', 'Project'), ('publication', 'Publication'), ('skill', 'Skill'), ('bullet', 'Bullet (Honors / Awards / Talks)'), ('normal', 'Normal Text'), ('one_line', 'One-Line')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume.resumeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list, help_text='List of author name strings. Wrap your name in *asterisks*.')),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('date', models.CharField(blank=True, help_text='YYYY-MM or YYYY', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Optional project URL — will be hyperlinked in PDF')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('single_date', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NormalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('single_date', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, help_text='"present" or YYYY-MM', max_length=20)),
                ('single_date', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=200)),
                ('degree', models.CharField(blank=True, help_text='e.g. BS, MS, PhD', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, help_text='YYYY-MM or YYYY', max_length=20)),
                ('end_date', models.CharField(blank=True, help_text='YYYY-MM, YYYY, or "present"', max_length=20)),
                ('single_date', models.CharField(blank=True, help_text='For a fixed date instead of range', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list, help_text='List of bullet-point strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.TextField(help_text='Bullet text (Markdown supported)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Programming Languages"', max_length=200)),
                ('details', models.CharField(help_text='e.g. "Python, C++, Rust"', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='resume.resumesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Instagram', 'Instagram'), ('ORCID', 'ORCID'), ('ResearchGate', 'ResearchGate'), ('Twitter', 'Twitter'), ('Mastodon', 'Mastodon'), ('StackOverflow', 'StackOverflow'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp'), ('WeChat', 'WeChat'), ('LINE', 'LINE'), ('Medium', 'Medium'), ('Substack', 'Substack'), ('HackerNews', 'HackerNews'), ('Reddit', 'Reddit')], max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='resume.resumeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
