# Generated by Django 6.0.6 on 2026-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationentry',
            name='gpa',
            field=models.CharField(blank=True, help_text='e.g. GPA: 3.8/4.0 or 85%', max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('ember', 'Ember'), ('engineeringclassic', 'Engineering Classic'), ('engineeringresumes', 'Engineering Resumes'), ('harvard', 'Harvard'), ('ink', 'Ink'), ('moderncv', 'Modern CV'), ('opal', 'Opal'), ('sb2nov', 'SB2Nov')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='selected_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('ember', 'Ember'), ('engineeringclassic', 'Engineering Classic'), ('engineeringresumes', 'Engineering Resumes'), ('harvard', 'Harvard'), ('ink', 'Ink'), ('moderncv', 'Modern CV'), ('opal', 'Opal'), ('sb2nov', 'SB2Nov')], default='classic', max_length=50),
        ),
    ]
