# Generated by Django 6.0.6 on 2026-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_educationentry_gpa_alter_generatedresume_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='resume_data',
            field=models.JSONField(blank=True, help_text='JSON snapshot of the resume data at generation time', null=True),
        ),
    ]
