# Generated by Django 6.0.6 on 2026-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_percentage',
            field=models.IntegerField(default=42),
        ),
    ]
